name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      matrix:
        elixir: ["1.14.3"]
        otp: ["25.2.3"]

    # Remove if you don't need a database
    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-flags: --all-warnings --warnings-as-errors

      # Run if you have a database
      - name: Run Migrations
        run: mix ecto.create ; mix ecto.migrate 
        # Run tests & migrations even if compilation failed (probably due to warnings)
        # so that we give devs as much feedback as possible & save some time.
        if: false

      - name: Run Tests
        run: mix coveralls.json --warnings-as-errors
        if: always()